[phases.setup]
nixPkgs = ['php82', 'nodejs-18_x']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'echo "=== Build complete, checking manifest ==="',
    'ls -lah public/build/',
    'test -f public/build/.vite/manifest.json && echo "✓ Manifest found" || echo "✗ Manifest missing"',
    'mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'
