[phases.setup]
nixPkgs = ['php82', 'nodejs-18_x']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
