[phases.setup]
nixPkgs = ['php82', 'nodejs-18_x']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'ls -lah public/build/',
    'php artisan config:cache',
    'php artisan route:cache'
]

[start]
cmd = 'php artisan view:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
